faq.md
Hey Marcel, this is a first draft for the faqs for the doc. I guess adding the menu item is not possible in this repo right? Let me know what you think about it. Guess it is a good start.
=> Add first faqs draft

configuration.md
I just setup a BotMan Slack integration for the first time and noticed that it is good to know where to find the Slack integrations.
=> Add Slack config information

configuration.md
Changes in not obvious part of Telegram configuration. 
I didn't read through it carefully and spend like 5 hours to find it out, maybe it will save some time to other people like me.
=> Telegram configuration fixes

sending.md
This needs mpociot/botman#220 to be released first
=> Add use case for uploading file to Slack (RTM)

nlp.md
New middleware system requires different setup for NLP middleware
=> Update nlp.md to reflect new middleware system

conversations.md
Add documentation for the skip and stop methods. Inside conversations as well as outside.
=> Add docs for skip and stop

sending.md
Added the info about how to get the FB postback btn text in the callback. We had this question multiple times now I guess.
=> Add info about how to get FB postback btn text

conversations.md
suggest in https://github.com/botman/botman/issues/481
=> Added Warning to use an Cache Driver in Conversations

user-information.md
This PR add information about caching users to the docs.
=> Add user cache information

driver-facebook-messenger.md
Added more details regarding the Facebook driver installation in case of BotMan Studio
=> Details regarding Facebook driver installation

driver-facebook-messenger.md
I basically copy/pasted from the upgrade guide, I believe this info need to be also in the facebook driver for all people not looking into the upgrade guide.
=> added docs to react to Optin or Referral events

testing.md
Added new methods from [approved PR](https://github.com/botman/studio-addons/pull/6) and [new PR ](https://github.com/botman/studio-addons/pull/10)
=> New methods

driver-telegram.md
There's no need to hide the existence of the command 😄
=> Explain command to register Telegram webhook

user-information.md
=> Fixing the comments

driver-web.md
There is a little sentence that shouldn't be there or :)?
=> Remove "WeChat" Sentence from Web Driver

driver-facebook-messenger.md
This PR adds info about the new FB Media Template
=> Add media template docs

conversations.md
More and more people ask about this and we think we should add it to the docs. Couldn't think of a better new conversation class than `FavouriteLunchConversation` connected to the onboarding topic. Feel free to change that :-)
=> Add info about starting a conversation from another one

receiving.md
see: https://github.com/botman/botman/pull/693
=> Updated docs on multiple recipients group command

drivers.md
Adds documentation for adding a custom BotMan driver.
=> Document custom drivers

driver-facebook-messenger.md, driver-telegram.md
A user contacted me because he didn't understand where to put the Telegram token. He was right that the explanation wasn't that well. I cleared things up for the Telegram and Facebook.
=> Update information update token in environment files

sending.md
https://github.com/botman/botman/issues/155
=> Update say method for Skype

faq.md
This is also my first PR so I thought I'd start with something easy :)
=> Fix typo in documentation faq

driver-amazon-alexa.md, driver-cisco-spark.md, driver-hangouts-chat.md, driver-hipchat.md, driver-ms-bot-framework.md, driver-nexmo.md, driver-slack.md, driver-twilio.md, driver-wechat.md
Previous PR fixes the typo in Telegram Driver. After that I realised the typo was in almost the other drivers, so this one doesn't include the telegram fix.
=> Fix typo in all the other drivers.

welcome.md
Fix the links to hearing and sending menssages
=> Fix links in wellcome.md

driver-facebook-messenger.md
I've just added the missing ":" to the command.
=> Fixed AddStartButton command

driver-facebook-messenger.md
This PR updates the command doc for the facebook driver.
=> Update facebook docs
